### ISSUE TITLE
StackOverflowError thrown due to Go interfaces extending themselves

### ISSUE THREAD

**Issue by Zir0-93** [Zir0-93/clarpse#74]
Stack trace:
```
java.lang.StackOverflowError
	at com.clarity.sourcemodel.Component.componentInvocations(Component.java:215)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:196)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
	at com.clarity.compiler.ImplementedInterfaces.getListOfMethodSpecs(ClarpseGoCompiler.java:199)
       .....
```

**Comment by Zir0-93** [comment]
closed by #75
